<script setup lang="ts">
import { inject, onMounted, ref } from "vue";
import type { PluginCtx } from "../../shell/ctx"; import { useLayoutStore } from "../../stores/layout"; import type { Chat, ChatList } from "./types"; import { errorText } from "./types";
const injectedCtx = inject<PluginCtx>("pluginCtx"); if (injectedCtx === undefined) throw new Error("ChatsPanel requires PluginPaneHost"); const ctx: PluginCtx = injectedCtx; const layout = useLayoutStore(); const chats = ref<Chat[]>([]); const active = ref(""); const root = ref(""); const name = ref("New Chat"); const error = ref("");
async function load(){const value=await ctx.bus.request("chat:_:chats:list",{}) as ChatList; chats.value=value.chats; active.value=value.active_chat_id}
async function create(){try{const chat=await ctx.bus.request("chat:_:chats:create",{name:name.value,root:root.value,type:"group",member_role_ids:[]}) as Chat; await activate(chat.id)}catch(cause){error.value=errorText(cause)}}
async function patch(chat:Chat, values:Record<string,unknown>){try{await ctx.bus.request("chat:_:chats:patch",{id:chat.id,...values});await load()}catch(cause){error.value=errorText(cause)}}
async function remove(chat:Chat){if(!confirm(`Delete ${chat.name}?`))return;try{await ctx.bus.request("chat:_:chats:delete",{id:chat.id});await load()}catch(cause){error.value=errorText(cause)}}
async function activate(id:string){await ctx.bus.request("chat:_:chats:activate",{id});active.value=id;layout.openInstance("chat",id)}
function rename(chat:Chat){const value=window.prompt("Name",chat.name);if(value!==null)void patch(chat,{name:value})}
onMounted(()=>void load().catch(cause=>error.value=errorText(cause)));
</script>
<template><section class="p-2 h-100 overflow-auto"><h6>Chats</h6><div v-if="error" class="text-danger small">{{error}}</div><div class="input-group input-group-sm mb-2"><input v-model="name" class="form-control" placeholder="Name"><input v-model="root" class="form-control" placeholder="Absolute root"><button class="btn btn-primary" title="New chat" @click="create"><i class="bi-plus-lg" /></button></div><div v-for="chat in chats" :key="chat.id" class="d-flex align-items-center gap-1 p-1 mb-1" :class="chat.id===active?'bg-primary-subtle':''"><button class="btn btn-sm text-start flex-grow-1" @click="activate(chat.id)">{{chat.pinned?'★ ':''}}{{chat.name}}<small class="d-block text-secondary">{{chat.root}}</small></button><button class="btn btn-sm" title="Pin" @click="patch(chat,{pinned:!chat.pinned})"><i class="bi-pin-angle" /></button><button class="btn btn-sm" title="Rename" @click="rename(chat)"><i class="bi-pencil" /></button><button class="btn btn-sm text-danger" title="Delete" @click="remove(chat)"><i class="bi-trash" /></button></div></section></template>
